ALTER TABLE PROPERTY DROP CONSTRAINT PROPERTY_NAME_ENUM;
INSERT INTO PROPERTY VALUES('COLORS', '#00FF00;#FF0000;#0000FF');
ALTER TABLE PROPERTY ADD CONSTRAINT PROPERTY_NAME_ENUM CHECK ("NAME" IN (
	'COLORS',
    'WELCOME_TEXT'
));